### ISSUE TITLE
Getting users blocked by current user only

### ISSUE THREAD

**Issue by mercExec** [multicaret/laravel-acquaintances#103]
Hello

Is there a way to get all users that have been blocked by the current user (sender) only? getBlockedFriendships() returns records with user ID found in both 'sender' or 'receiver', so if both users blocked each other, they will have their own model returned as well.

I had to modify the method from this:
`return $this->getOrPaginate($this->findFriendships(Status::BLOCKED), $perPage, $fields);`
to this
`return $this->getOrPaginate($this->findFriendships(Status::BLOCKED, type: 'sender'), $perPage, $fields);`

**Comment by mkwsra** [comment]
Hey there, thanks for using this library, if you wish you can create two functions and send them as a PR, and I will check it out and merge it

**Comment by mercExec** [comment]
Done. Function names could be changed since I'm terrible with naming conventions. 
Anyway, thank you for developing this library; it's the best one of all the libraries i found that serve the same purpose.

**Comment by mkwsra** [comment]
Thanks Merc so much for your contribution and for your nice words, I just published a new release v3.5.9

**Comment by AntKovachev** [comment]
@mkwsra, should this issue still be with status open? Is there anything else that needs to be done?

**Comment by mkwsra** [comment]
No, thanks, I will close it immediately
